spring:
  profiles:
    active: "admin,operate,tasklist,broker,consolidated-auth"

management:
  server:
    port: 9600
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,configprops
  endpoint:
    configprops:
      show-values: ALWAYS

server:
  forward-headers-strategy: framework
  address: 0.0.0.0

zeebe:
  host: 0.0.0.0
  log:
    level: "info"

  broker:
    gateway:
      enable: true

camunda:
  api:
    grpc:
      address: 0.0.0.0
      port: 26500
  cluster:
    network:
      host: 0.0.0.0
      command-api:
        port: 26501
      internal-api:
        port: 26502
  system:
    cpu-thread-count: 4
    io-thread-count: 4
  data:
    primary-storage:
      directory: /usr/local/camunda/data
      snapshot-period: 5m
      disk:
        free-space:
          processing: 2GB
          replication: 1GB
    secondary-storage:
      type: rdbms
      rdbms:
        url: "jdbc:postgresql://camunda-db:5432/camunda"
        username: "camunda"
        password: "${CAMUNDA_DB_PASSWORD}"
    exporters:
      elasticsearch:
        class-name: io.camunda.zeebe.exporter.ElasticsearchExporter
        args:
          url: "http://elasticsearch:9200"
          bulk:
            delay: 5
            size: 1000
            memoryLimit: 10485760
          retention:
            enabled: true
            minimumAge: 90d
            policyName: zeebe-records-retention-policy
          index:
            prefix: zeebe-record
            createTemplate: true
            indexSuffixDatePattern: "yyyy-MM-dd"
            numberOfShards: 1
            numberOfReplicas: 0
            optimizeModeEnabled: true
  backup:
    webapps:
      enabled: false
  persistent:
    sessions:
      enabled: true

  rest:
    query:
      enabled: true

  mcp:
    enabled: true

  security:
    authentication:
      method: "oidc"
      unprotectedApi: false
    authorizations:
      enabled: true
    initialization:
      defaultRoles:
        admin:
          users:
            - demo
          clients:
            - orchestration
        connectors:
          users:
            - connectors
          clients:
            - connectors

  operate:
    persistentSessionsEnabled: true
    identity:
      redirectRootUrl: "https://orchestration.${HOST}/operate"
    archiver:
      ilmEnabled: true
      ilmMinAgeForDeleteArchivedIndices: 90d

  tasklist:
    identity:
      redirectRootUrl: "https://orchestration.${HOST}/tasklist"
    archiver:
      ilmEnabled: true
      ilmMinAgeForDeleteArchivedIndices: 90d
